version: 2.1

orbs:
  maven: circleci/maven@1.1.0
  docker: circleci/docker@1.5.0

workflows:
  build:
    jobs:
      - maven/test:
          command: package
      - docker/hadolint:
          trusted-registries: docker.io
          requires:
            - maven/test
      - docker/publish:
          attach-at: './'
          image: ${DOCKER_LOGIN}/udacity-cloud-devops-spring-petclinic
          tag: 1.0.0-b${CIRCLE_BUILD_NUM}
          context: udacity
          requires:
            - docker/hadolint
