version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: ./mvnw package
      - persist_to_workspace:
         root: ./
         paths:
           - target/
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  build:
    jobs:
      - build
      - docker/hadolint:
          trusted-registries: docker.io
          requires:
            - build
      - docker/publish:
          attach-at: './'
          image: ${DOCKER_LOGIN}/udacity-cloud-devops-spring-petclinic
          tag: 1.0.0-b${CIRCLE_BUILD_NUM}
          context: udacity
          requires:
            - docker/hadolint
