version: 2.1

orbs:
  maven: circleci/maven@1.1.0
  docker: circleci/docker@1.5.0

workflows:
  maven_test:
    jobs:
      - maven/test
  lint:
    jobs:
      - docker/hadolint:
          trusted-registries: docker.io