version: 2.1

orbs:
  maven: circleci/maven@1.1.0
  docker: circleci/docker@1.5.0

workflows:
  maven_test:
    jobs:
      - maven/test
  lint:
    jobs:
      - docker/hadolint:
          trusted-registries: docker.io
      - docker/publish:
          image: ${DOCKER_LOGIN}/udacity-cloud-devops-spring-petclinic
          tag: 1.0.0-b${CIRCLE_BUILD_NUM}
          context: udacity
          requires:
            docker/hadolint
