version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2
  anchore-engine: anchore/anchore-engine@1.0.0

jobs:
  maven_build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: ./mvnw package
      - persist_to_workspace:
         root: ./
         paths:
           - target/
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  build:
    jobs:
      - maven_build
      - docker/hadolint:
          trusted-registries: docker.io
          requires:
            - maven_build
      - docker/publish:
          attach-at: './'
          image: ${DOCKER_LOGIN}/udacity-cloud-devops-spring-petclinic
          tag: 1.0.0-b${CIRCLE_BUILD_NUM}
          context: udacity
          requires:
            - docker/hadolint
      - aws-eks/update-container-image:
          aws-region: eu-west-1
          cluster-name: udacity
          container-image-updates: "petclinic=${DOCKER_LOGIN}/udacity-cloud-devops-spring-petclinic:1.0.0-b${CIRCLE_BUILD_NUM}"
          get-rollout-status: true
          namespace: petclinic
          resource-name: deployment/petclinic
          record: true
          show-kubectl-command: true
          watch-timeout: 5m
          requires:
            - "docker/publish"
      - anchore/image_scan:
          image_name: "${DOCKER_LOGIN}/udacity-cloud-devops-spring-petclinic:1.0.0-b${CIRCLE_BUILD_NUM}"
          timeout: '600'
          requires:
            - "docker/publish"

