apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
    version: 1.0.0-b30
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  strategy: 

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic
    spec:
      containers:
      - image: fnan/udacity-cloud-devops-spring-petclinic:1.0.0-b30
        name: petclinic
        ports:
        - containerPort: 8080
        resources: {}
status: {}
